### ISSUE TITLE
Reduce the number of genome assembly downloads 

### ISSUE THREAD

**Issue by ljmesi** [genomic-medicine-sweden/gmsmetapost#28]
### Description of feature

When taxonomy classifications produce taxid which has many associated reference assemblies, it would be good to try to reduce the number of genomes that will be downloaded. E,g with `datasets download genome taxon 11676` the number of genomes to be downloaded is around 500.

**Comment by sofstam** [comment]
@ljmesi Maybe we could use the Entrez records (Genome) https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=info&id=11676

In the case you mentioned, https://www.ncbi.nlm.nih.gov/genome/?term=txid11676[Organism:exp]

**Comment by ljmesi** [comment]
@sofstam Yes, that could be useful too. Another approach which is implemented in #49 there will be no need to download anything over the internet as the only location from which the fasta sequences are retrieved are from a local BLAST nt database. It's also good that there is an easy way to update the local BLAST nt database with blast's own utility scripts.

**Comment by sofstam** [comment]
Sounds good to me!
