### ISSUE TITLE
Use some other account for hosting singularity images than library://ljmesi/gmsmetapost/

### ISSUE THREAD

**Issue by ljmesi** [genomic-medicine-sweden/gmsmetapost#40]
### Description of feature

The most optimal would be to switch to singularity images hosted on:
https://depot.galaxyproject.org/singularity

**Comment by sofstam** [comment]
As we talked in-person, we could test to remove the authentication token to verify that the pipeline works by using the singularity image.

**Comment by ljmesi** [comment]
@sofstam, maybe this can be closed due to PR: #73, right?

**Comment by sofstam** [comment]
Yes!
